### ISSUE TITLE
Mocking about may break the selectedMenu

### ISSUE THREAD

**Issue by Rhineheart** [eGovlab/sense4us-simulation#19]
Deleting, saving and loading models may break the selectedMenu where the map will get undefined somehow. Don't have steps to reproduce.

**Comment by saikyun** [comment]
Might be because of my changes to selected menu. It behaves oddly if you
add attributes without recreating the menu.

**Comment by Rhineheart** [comment]
Now it just fucks itself up without any kind of special interaction. I deem this quite important so I will prioritize it now.

**Comment by Rhineheart** [comment]
commit 0a604c09181bcc572b840c3f2444177604f15fdc
Date:   Mon Jul 27 15:11:16 2015 +0200

Three hours ago? wut. Oh well, it should not break now. Probably. Maybe.
