### ISSUE TITLE
A white background

### ISSUE THREAD

**Issue by osemsem** [eGovlab/sense4us-simulation#20]
A white background for the causal map graphing canvas to suit the new icon set for (controllable origins- policy instruments), (Actors), (Uncontrollable origins - External factors and constraints) and the (nodes - impact variables) respectively as they appear on the left panel of the attached screenshot.
![interface](https://cloud.githubusercontent.com/assets/12909055/8696939/2a30873e-2af1-11e5-883e-bc310ea17800.png)
The labels for the nodes appearing in the above picture (Letters) are not the way we have labels,  labels are always below the nodes.

**Comment by Rhineheart** [comment]
Commit: 204acacb4df072e824d7cf5a680ef0d489236b7d
Date: Mon Jul 27 14:14:43 2015

The background is now white.

**Comment by osemsem** [comment]
Thanks.
make sure we use the icon set as shown in the above screenshot in the right way.
Please publish the latest version so that we can see the updates.

**Comment by Rhineheart** [comment]
I will at the end of the day. I am making more changes and fixing bugs/removing bugged features.
