### ISSUE TITLE
Half channels and full channels

### ISSUE THREAD

**Issue by osemsem** [eGovlab/sense4us-simulation#22]
Only one type of channels is implemented right now. 

I will send today 15-07-2015 a document providing description of the model components, the nodes with the new icon set, the difference between half channels and full channels, a procedure for creating a model, editing link properties and node properties and triggering scenarios.

**Comment by Rhineheart** [comment]
The half-channels are implemented in the unreviewed branch. No pull request made on it yet.

**Comment by Rhineheart** [comment]
I don't remember when or how it was implemented.
