### ISSUE TITLE
Labels for the different types of variables

### ISSUE THREAD

**Issue by osemsem** [eGovlab/sense4us-simulation#66]
Please use the following labels, repectively: 
- "Policy instruments" instead of "independent variables"
- "External factors and constraints" insstead of "uncontrollable sources"
- "Impact variables" instead of "dependent variables"
- "Policy problem" instead of "name"
- "Maximum number of iterations" should be in the same place with the time step, since we are using discrete time steps in terms of a predefined time unit, then, instead of week/month/year make the time unit here any number of weeks/months/years and all times are then expressed in this unit.

**Comment by Rhineheart** [comment]
Everything is live except the max iterations. But those are updated in the unreviewed branch. I'll update the server very soon.
