### ISSUE TITLE
Size of the nodes and arrows

### ISSUE THREAD

**Issue by osemsem** [eGovlab/sense4us-simulation#67]
The size of the node is quite big here also the width of the arrows can you make them smaller (reduced to 75% of the current size). because it is not possible to zoom in or out.

**Comment by osemsem** [comment]
also if possible to show the change transfer coefficient and time lag together next to the link. e.g., 0.25 (0) means coefficient = 0.25 and time lag=0; 1.2 (3) means coefficient=1.2 and time lag=3.

**Comment by Rhineheart** [comment]
Should be fixed in an unreviewed commit. Will add some kind of settings menu someday.
