### ISSUE TITLE
Important - missing feature the threshold value

### ISSUE THREAD

**Issue by osemsem** [eGovlab/sense4us-simulation#69]
There is a feature missing in the prototype - a minimum threshold value for each transmission channel below which no change is transferred, preferably having this condition on the accumulated change at the upstream node.. 
For example, if the minimum threshold for the change in the upstream variable is +20%, then any change can't be transferred from that variable if its accumulated change is below +20%.

**Comment by Rhineheart** [comment]
This is implemented in remove_immutable-branch. Also running online.
