### ISSUE TITLE
The time unit should appear with the maximum number of iterations in the same place.

### ISSUE THREAD

**Issue by osemsem** [eGovlab/sense4us-simulation#70]
Because defining time lags for the model needs the time unit to be defined first. and for the slider in the simulation mode you can display the time unit and the number of iterations again.

**Comment by Rhineheart** [comment]
Now there is a current value and a max value on the slider. The max value will also change when maxIterations is changed.

http://memset.se/353/7508200a98cde227b902

See print.

Will update server soon.
