### ISSUE TITLE
Scenario editor for models

### ISSUE THREAD

**Issue by Rhineheart** [eGovlab/sense4us-simulation#78]
Edit and save different timetables for a model. Sort by policy instrument and external factors.

**Comment by osemsem** [comment]
In the scenario editor, T should start by T0 and instead of V use C 'change' and put % right to the field

**Comment by Rhineheart** [comment]
Ah, missed that it starts by 1 in an empty table. Will fix.

Sure.

**Comment by Rhineheart** [comment]
Now says C, got a % to the right and starts from 0 in an empty table.
