### ISSUE TITLE
Actors

### ISSUE THREAD

**Issue by Rhineheart** [eGovlab/sense4us-simulation#79]
Do we have this issue already?

Actors should be able to define a goal, but shouldn't influence the model as of now. They will be used to generate analysis data.

**Comment by osemsem** [comment]
As of now, actors are just coupled with policy instruments, to know who controls what.
Scenarios are created anyway by the user for both controllable and uncontrollable origins

**Comment by Rhineheart** [comment]
Implemented in #86
