### ISSUE TITLE
Adding icons for actors, @Robin: please prioritize this for next week's workshop.

### ISSUE THREAD

**Issue by osemsem** [eGovlab/sense4us-simulation#84]
Add three new components:
Executive actors: the guy with a podium behind him :)
Legislative actor: Parliament 
Unofficial actor: Stakeholders
With a possibility to link them to policy instruments (by highlighting with the same color or by dashed arrows) or maybe just the possibility to add them to the canvas and linking them in the properties of the component.
![executive actor](https://cloud.githubusercontent.com/assets/12909055/13027430/4b2741ec-d250-11e5-855e-2695c1c761f8.png)
![legislative actor](https://cloud.githubusercontent.com/assets/12909055/13027564/3d74429e-d254-11e5-99c8-71e7b599078e.png)
![unofficial actor](https://cloud.githubusercontent.com/assets/12909055/13027565/41cc86b2-d254-11e5-87dd-912940e01270.png)

**Comment by osemsem** [comment]
Example with the actors added to a model
![3](https://cloud.githubusercontent.com/assets/12909055/13032855/afdba782-d303-11e5-8fec-daa684b4aaac.png)

**Comment by Rhineheart** [comment]
Sure, I'm picking this up now. Will grab Anton and rewrite some things before implementation.

**Comment by Rhineheart** [comment]
Implemented in #86
