### ISSUE TITLE
Right click and drag to make links.

### ISSUE THREAD

**Issue by Rhineheart** [eGovlab/sense4us-simulation#87]

**Comment by Rhineheart** [comment]
379570913bc5d4bc84d3a5e5cf46460d2cb6e869

**Comment by osemsem** [comment]
It suddenly stops working, then I have to delete the element them it happens to another

**Comment by Rhineheart** [comment]
Do you know how to reproduce the issue?

**Comment by Rhineheart** [comment]
It's fucked again after removing object hack.

**Comment by Rhineheart** [comment]
It's up and running.
